SRCS = main.c \
	src/builtins/builtins_core.c \
	src/builtins/builtins_echo.c \
	src/builtins/builtins_cd.c \
	src/builtins/builtins_pwd.c \
	src/builtins/builtins_env.c \
	src/builtins/builtins_exit.c \
	src/utils/ft_strncmp.c \
	src/utils/ft_putstr_fd.c \
	src/utils/ft_atoi.c \
	# ... rest of source files ...

# ... rest of Makefile ... 